#
# GitHub Actions workflow configuration.
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
#

name: Source
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/heads/pull-request/') }}
defaults:
  run:
    shell: nix develop --command bash -e {0}
jobs:
  nix:
    name: nix
    permissions:
      contents: read
    runs-on: linux-amd64-cpu16
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Build cache.
      - id: build-cache
        uses: actions/cache@v5
        with:
          key: ${{ github.job }}-${{ hashFiles('.cachekeep', 'flake.lock', 'flake.nix', 'nix/**/*') }}
          path: |
            -
            .cachekeep
      # Install Nix.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          summarize: false
      # Main.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        working-directory: nix
        run: |
          just build
  multi-storage-explorer:
    name: multi-storage-explorer
    permissions:
      contents: read
    runs-on: linux-amd64-cpu16
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Build cache.
      - id: build-cache
        uses: actions/cache@v5
        with:
          key: ${{ github.job }}-${{ hashFiles('.cachekeep', 'flake.lock', 'flake.nix', 'nix/**/*', 'multi-storage-explorer/**/*') }}
          path: |
            -
            .cachekeep
      # Install Nix.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          summarize: false
      # Main.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        working-directory: multi-storage-explorer
        run: |
          just build
  multi-storage-client:
    name: multi-storage-client
    permissions:
      contents: read
    strategy:
      matrix:
        python-binary:
          - python3.10
          - python3.11
          - python3.12
          - python3.13
      fail-fast: false
    runs-on: linux-amd64-cpu16
    defaults:
      run:
        shell: nix develop ${{ github.workspace }}#"\"${{ matrix.python-binary }}\"" --command bash -e {0}
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Build cache.
      - id: build-cache
        uses: actions/cache@v5
        with:
          key: ${{ github.job }}-${{ matrix.python-binary }}-${{ hashFiles('flake.lock', 'flake.nix', 'nix/**/*', 'pyproject.toml', 'uv.lock', 'multi-storage-explorer/**/*', 'multi-storage-client/**/*') }}
          path: |
            -
            multi-storage-client/.reports/unit/coverage/
            multi-storage-client/dist/
      # Install Nix.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          summarize: false
      # Main.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        working-directory: multi-storage-explorer
        run: |
          just bundle
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        working-directory: multi-storage-client
        run: |
          just python-binary=${{ matrix.python-binary }} build
          just python-binary=${{ matrix.python-binary }} run-minimal-verification
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        working-directory: multi-storage-client-scripts
        run: |
          # TODO: After MSC 1.0 is released, fetch the 1.0 tag used by check-api-compat.
          git fetch --no-tags --prune origin main:refs/remotes/origin/main
          uv run msc-scripts check-api-compat
      - uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: ${{ github.job }} (${{ matrix.python-binary }})
          path: |
            -
            multi-storage-client/.reports/unit/coverage/
            multi-storage-client/dist/
  multi-storage-client-docs:
    name: multi-storage-client-docs
    permissions:
      contents: read
    runs-on: linux-amd64-cpu16
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Build cache.
      - id: build-cache
        uses: actions/cache@v5
        with:
          key: ${{ github.job }}-${{ hashFiles('flake.lock', 'flake.nix', 'nix/**/*', 'pyproject.toml', 'uv.lock', 'multi-storage-client/**/*', 'multi-storage-client-docs/**/*') }}
          path: |
            -
            multi-storage-client-docs/dist/
      # Install Nix.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          summarize: false
      # Main.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        working-directory: multi-storage-client-docs
        run: |
          just build
      - uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: ${{ github.job }}
          path: |
            -
            multi-storage-client-docs/dist/
  multi-storage-client-scripts:
    name: multi-storage-client-scripts
    permissions:
      contents: read
    runs-on: linux-amd64-cpu16
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Build cache.
      - id: build-cache
        uses: actions/cache@v5
        with:
          key: ${{ github.job }}-${{ hashFiles('.cachekeep', 'flake.lock', 'flake.nix', 'nix/**/*', 'pyproject.toml', 'uv.lock', 'multi-storage-client-scripts/**/*') }}
          path: |
            -
            .cachekeep
      # Install Nix.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          summarize: false
      # Main.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        working-directory: multi-storage-client-scripts
        run: |
          just build
  multi-storage-file-system:
    name: multi-storage-file-system
    permissions:
      contents: read
    runs-on: linux-amd64-cpu16
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Build cache.
      - id: build-cache
        uses: actions/cache@v5
        with:
          key: multi-storage-file-system-${{ hashFiles('flake.lock', 'flake.nix', 'nix/**/*', 'multi-storage-client/pyproject.toml', 'multi-storage-file-system/**/*') }}
          path: |
            -
            multi-storage-file-system/build/debian/archives/*.deb
            multi-storage-file-system/build/rpm/RPMS/*/*.rpm
            multi-storage-file-system/build/tar/*.tar.*
            multi-storage-file-system/build/zip/*.zip
      # Install Nix.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          summarize: false
      # Main.
      - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
        working-directory: multi-storage-file-system
        run: |
          just build
      - uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: ${{ github.job }}
          path: |
            -
            multi-storage-file-system/build/debian/archives/*.deb
            multi-storage-file-system/build/rpm/RPMS/*/*.rpm
            multi-storage-file-system/build/tar/*.tar.*
            multi-storage-file-system/build/zip/*.zip
  check-publish-release-inputs:
    name: Check Publish Release Inputs
    needs:
      - nix
      - multi-storage-explorer
      - multi-storage-client
      - multi-storage-client-docs
      - multi-storage-client-scripts
      - multi-storage-file-system
    permissions:
      contents: read
    runs-on: linux-amd64-cpu16
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Install Nix.
      - uses: DeterminateSystems/determinate-nix-action@v3
        with:
          summarize: false
      # Main.
      #
      # All `actions/upload-artifact` paths must include a `-` path to preserve workspace structure.
      #
      # https://github.com/actions/upload-artifact/issues/174
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      - working-directory: multi-storage-client-scripts
        run: |
          uv run msc-scripts publish-release --github-token ${{ secrets.GITHUB_TOKEN }} --phase check
